/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailtester;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintStream;
import java.net.InetAddress;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.NoSuchProviderException;
import javax.mail.internet.AddressException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Mauros
 */
public class initWindow extends javax.swing.JFrame {
    
    private String inicio_w =" \n█▀▄▀█ █▀▀█ ─▀─ █── ▀▀█▀▀ █▀▀ █▀▀ ▀▀█▀▀ █▀▀ █▀▀█ \n█─▀─█ █▄▄█ ▀█▀ █── ─░█── █▀▀ ▀▀█ ──█── █▀▀ █▄▄▀ \n▀───▀ ▀──▀ ▀▀▀ ▀▀▀ ─░█── ▀▀▀ ▀▀▀ ──▀── ▀▀▀ ▀─▀▀";
    private String info_w;
    private String logs_w;
    /**
     * Creates new form initWindow
     */
    
                public ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();

            // Crie um PrintStream personalizado para escrever na ByteArrayOutputStream
            public PrintStream printStream = new PrintStream(byteArrayOutputStream);

            // Redirecione a saída padrão para o PrintStream personalizado
    
    public initWindow() throws NoSuchProviderException, AddressException {
        initComponents();
        atualizaCampos();
        desabilitaCampos();
        imageIcon();
        jLabel45.setVisible(false);
jLabel29.setVisible(false);


            System.setOut(printStream);
        logs_w += "\n\n";
        logs_w += byteArrayOutputStream.toString();
        jTextPane1.setText(logs_w);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField5 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        porta_w = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        protocolo_w = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        linha1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        dominioDestino_w = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        host_2 = new javax.swing.JLabel();
        Host = new javax.swing.JLabel();
        protocolo_1 = new javax.swing.JLabel();
        linha = new javax.swing.JLabel();
        porta_1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        protocolo_2 = new javax.swing.JLabel();
        dominiodestino_1 = new javax.swing.JLabel();
        cifra_2 = new javax.swing.JLabel();
        host_1 = new javax.swing.JLabel();
        dominiodestino_2 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        cifra_1 = new javax.swing.JLabel();
        host_w = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        porta_2 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        salvar_b = new javax.swing.JButton();
        copiar_b = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        parametro = new javax.swing.JLabel();
        logs_b1 = new javax.swing.JToggleButton();
        jLabel58 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Email Tester 2.0");
        setMaximumSize(new java.awt.Dimension(850, 640));
        setMinimumSize(new java.awt.Dimension(850, 640));
        setPreferredSize(new java.awt.Dimension(850, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 340, 30));

        jLabel1.setText("REMETENTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        jTextField2.setEnabled(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField2MouseExited(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, 30));

        jLabel2.setText("Protocolo (Segurança)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "587", "465", "2525", "25", "Definir>" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 30));

        jLabel3.setText("SERVIDOR SMTP (HOST)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jTextField3.setForeground(new java.awt.Color(51, 153, 0));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField3MouseExited(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 30));

        jLabel4.setText("IDENTIFICADOR DO USUÁRIO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField4MouseExited(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 340, 30));

        jLabel5.setText("SENHA DO USUÁRIO");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 20));

        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField6MouseExited(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 340, 30));

        jLabel6.setText("DESTINATÁRIO");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        jTextField7.setEditable(false);
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField7MouseExited(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 340, 30));

        jLabel7.setText("DOMINIO DESTINO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        jTextField8.setText("Teste de envio de e-mail.");
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField8MouseExited(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 340, 30));

        jLabel8.setText("TITULO DO E-MAIL");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 20));

        jLabel9.setText("CORPO DO E-MAIL");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, 20));

        jTextField9.setText("Teste de envio de e-mail.");
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField9MouseExited(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 340, 30));

        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseExited(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, 30));

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Ocultar");
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseExited(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 244, -1, -1));

        jTextPane1.setEditable(false);
        jTextPane1.setText("\n█▀▄▀█ █▀▀█ ─▀─ █── ▀▀█▀▀ █▀▀ █▀▀ ▀▀█▀▀ █▀▀ █▀▀█ \n█─▀─█ █▄▄█ ▀█▀ █── ─░█── █▀▀ ▀▀█ ──█── █▀▀ █▄▄▀ \n▀───▀ ▀──▀ ▀▀▀ ▀▀▀ ─░█── ▀▀▀ ▀▀▀ ──▀── ▀▀▀ ▀─▀▀");
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 430, 520));

        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TLS", "SSL" }));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox3MouseExited(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 140, 30));

        jLabel11.setText("PORTA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 360, 10));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Porta:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 60, -1));

        porta_w.setBackground(new java.awt.Color(255, 255, 255));
        porta_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        porta_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        porta_w.setText("587");
        getContentPane().add(porta_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 60, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 80, 30));

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setOpaque(true);
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 180, 10));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setOpaque(true);
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 40, 10));

        protocolo_w.setBackground(new java.awt.Color(255, 255, 255));
        protocolo_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        protocolo_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        protocolo_w.setText("TLS");
        getContentPane().add(protocolo_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 60, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Protocolo:");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 60, -1));

        jLabel40.setBackground(new java.awt.Color(255, 255, 255));
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.setOpaque(true);
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 80, 30));

        jLabel43.setBackground(new java.awt.Color(0, 0, 0));
        jLabel43.setOpaque(true);
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 10, 10));

        linha1.setText("-");
        getContentPane().add(linha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 160, 140));

        jLabel44.setBackground(new java.awt.Color(0, 0, 0));
        jLabel44.setOpaque(true);
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 40, 10));

        jLabel46.setBackground(new java.awt.Color(153, 153, 153));
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setOpaque(true);
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 10, 10));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 60, 60));

        jLabel54.setBackground(new java.awt.Color(0, 0, 0));
        jLabel54.setOpaque(true);
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 10, 20));

        dominioDestino_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dominioDestino_w.setText("_");
        getContentPane().add(dominioDestino_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 170, 20));

        jLabel13.setText("-");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 60, 60));

        jLabel63.setBackground(new java.awt.Color(0, 0, 0));
        jLabel63.setOpaque(true);
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 80, 10));

        host_2.setBackground(new java.awt.Color(51, 204, 0));
        host_2.setForeground(new java.awt.Color(0, 153, 0));
        host_2.setEnabled(false);
        host_2.setOpaque(true);
        getContentPane().add(host_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 342, 180, 10));

        Host.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Host.setText("Host:");
        getContentPane().add(Host, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        protocolo_1.setBackground(new java.awt.Color(51, 204, 0));
        protocolo_1.setForeground(new java.awt.Color(0, 153, 0));
        protocolo_1.setEnabled(false);
        protocolo_1.setOpaque(true);
        getContentPane().add(protocolo_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 10, 40));

        linha.setText("jLabel15");
        getContentPane().add(linha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 160, 50));

        porta_1.setBackground(new java.awt.Color(51, 204, 0));
        porta_1.setForeground(new java.awt.Color(0, 153, 0));
        porta_1.setEnabled(false);
        porta_1.setOpaque(true);
        getContentPane().add(porta_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 10, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 170, 20));

        jLabel60.setBackground(new java.awt.Color(0, 0, 0));
        jLabel60.setOpaque(true);
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 80, 10));

        jLabel61.setBackground(new java.awt.Color(0, 0, 0));
        jLabel61.setOpaque(true);
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 10, 20));

        jLabel66.setBackground(new java.awt.Color(255, 255, 255));
        jLabel66.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Cifra");
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 60, -1));

        jLabel56.setBackground(new java.awt.Color(0, 0, 0));
        jLabel56.setOpaque(true);
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 10, 30));

        protocolo_2.setBackground(new java.awt.Color(51, 204, 0));
        protocolo_2.setForeground(new java.awt.Color(0, 153, 0));
        protocolo_2.setEnabled(false);
        protocolo_2.setOpaque(true);
        getContentPane().add(protocolo_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 80, 10));

        dominiodestino_1.setBackground(new java.awt.Color(51, 204, 0));
        dominiodestino_1.setForeground(new java.awt.Color(0, 153, 0));
        dominiodestino_1.setEnabled(false);
        dominiodestino_1.setOpaque(true);
        getContentPane().add(dominiodestino_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 10, 30));

        cifra_2.setBackground(new java.awt.Color(51, 204, 0));
        cifra_2.setForeground(new java.awt.Color(0, 153, 0));
        cifra_2.setEnabled(false);
        cifra_2.setOpaque(true);
        getContentPane().add(cifra_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 80, 10));

        host_1.setBackground(new java.awt.Color(51, 204, 0));
        host_1.setForeground(new java.awt.Color(0, 153, 0));
        host_1.setEnabled(false);
        host_1.setOpaque(true);
        getContentPane().add(host_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 10, 30));

        dominiodestino_2.setBackground(new java.awt.Color(51, 204, 0));
        dominiodestino_2.setForeground(new java.awt.Color(0, 153, 0));
        dominiodestino_2.setEnabled(false);
        dominiodestino_2.setOpaque(true);
        getContentPane().add(dominiodestino_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 170, 10));

        jLabel67.setBackground(new java.awt.Color(255, 255, 255));
        jLabel67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel67.setOpaque(true);
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 80, 30));

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setOpaque(true);
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 10, 150));

        cifra_1.setBackground(new java.awt.Color(51, 204, 0));
        cifra_1.setForeground(new java.awt.Color(0, 153, 0));
        cifra_1.setEnabled(false);
        cifra_1.setOpaque(true);
        getContentPane().add(cifra_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 10, 40));

        host_w.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        host_w.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        host_w.setText("_");
        getContentPane().add(host_w, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 180, -1));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel59.setOpaque(true);
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 180, 25));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 60, 60));

        jLabel22.setBackground(new java.awt.Color(204, 204, 204));
        jLabel22.setOpaque(true);
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 280, 120));

        jLabel72.setBackground(new java.awt.Color(0, 0, 0));
        jLabel72.setOpaque(true);
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 80, 10));

        porta_2.setBackground(new java.awt.Color(51, 204, 0));
        porta_2.setForeground(new java.awt.Color(0, 153, 0));
        porta_2.setEnabled(false);
        porta_2.setOpaque(true);
        getContentPane().add(porta_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 80, 10));

        jLabel64.setBackground(new java.awt.Color(0, 0, 0));
        jLabel64.setOpaque(true);
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 10, 50));

        jLabel45.setBackground(new java.awt.Color(0, 0, 0));
        jLabel45.setOpaque(true);
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 10, 110));

        jLabel65.setBackground(new java.awt.Color(204, 204, 204));
        jLabel65.setOpaque(true);
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 310, 200));

        jLabel57.setBackground(new java.awt.Color(0, 0, 0));
        jLabel57.setOpaque(true);
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 30, 10));

        jLabel68.setBackground(new java.awt.Color(153, 153, 153));
        jLabel68.setOpaque(true);
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 10, 10));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 240, 50));

        salvar_b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salvar_b.setText("Limpar");
        salvar_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_bActionPerformed(evt);
            }
        });
        getContentPane().add(salvar_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 90, -1));

        copiar_b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        copiar_b.setText("Copiar");
        copiar_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copiar_bActionPerformed(evt);
            }
        });
        getContentPane().add(copiar_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 10, 590));

        jToggleButton1.setText("Auto");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseExited(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 70, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Configurações do Usuário");
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 350, 20));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 10, 590));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 360, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Configurações do Host");
        jLabel16.setToolTipText("");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Configurações do E-mail");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 343, 350, 20));

        parametro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        parametro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parametro.setText("Desenvolvido por Mauros Milach, 2023.");
        getContentPane().add(parametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 460, -1));

        logs_b1.setText("Detalhes →");
        logs_b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logs_b1ActionPerformed(evt);
            }
        });
        getContentPane().add(logs_b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 30, 200));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 60, 60));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 110, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/refresh.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 70, 50));

        jMenu1.setText("Arquivo");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setText("Salvar Log");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Upload XML");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            jPasswordField1.setVisible(true);
            jPasswordField1.setText(jTextField5.getText());
            jTextField5.setVisible(false);
        }else{
            jPasswordField1.setVisible(false);
            jTextField5.setText(jPasswordField1.getText());
            jTextField5.setVisible(true);   
        }
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void imageIcon (){
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/server.png"));
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/imagens/network.png"));
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/imagens/lineA.gif"));
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/imagens/lineB.gif"));
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/imagens/refresh.png"));
        ImageIcon icon5 = new ImageIcon(getClass().getResource("/imagens/validate.png"));
    ImageIcon icon6 = new ImageIcon(getClass().getResource("/imagens/message.png"));        
        
        Image image = icon.getImage();
        Image image1 = icon1.getImage();
        Image image2 = icon2.getImage();
        Image image3 = icon3.getImage();
        Image image4 = icon4.getImage();
        Image image5 = icon5.getImage();
        Image image6 = icon6.getImage();
        
        Image ScaledImage = image.getScaledInstance(jLabel52.getWidth(), jLabel52.getHeight(), Image.SCALE_SMOOTH);
        Image ScaledImage1 = image1.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
        Image ScaledImage2 = image4.getScaledInstance(jButton3.getWidth()-25, jButton3.getHeight()-5, Image.SCALE_SMOOTH);
        Image ScaledImage3 = image5.getScaledInstance(jButton3.getWidth()-25, jButton3.getHeight()-5, Image.SCALE_SMOOTH);
        Image ScaledImage4 = image6.getScaledInstance(jButton2.getWidth()-175, jButton2.getHeight()-5, Image.SCALE_SMOOTH);
        

        ImageIcon img = new ImageIcon (ScaledImage);
        ImageIcon img1 = new ImageIcon (ScaledImage1);
        ImageIcon img2 = new ImageIcon (image2);
        ImageIcon img3 = new ImageIcon (image3);
        

  //      jLabel52 = new JLabel(icon);

        
     //   jLabel52 = new JLabel (img);
        jLabel52.setIcon(img);
jLabel10.setIcon(img);
jLabel13.setIcon(img1);
linha.setIcon(img2);
linha1.setIcon(img3);


linha1.setVisible(false);
linha.setVisible(false);


jButton3.setIcon(new javax.swing.ImageIcon(ScaledImage2));
jButton1.setIcon(new javax.swing.ImageIcon(ScaledImage3));
jButton2.setIcon(new javax.swing.ImageIcon(ScaledImage4));
    }
    
    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        
        info_w = "► Informe o endereço (DNS ou IP) do Servidor SMTP Remoto.\n\nEste campo é equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema\n\nExemplos:\n\n• Gmail: smtp.gmail.com" +
"\n" +
"• Microsoft: smtp.live.com" +
"\n" +
"• Yahoo: smtp.mail.yahoo.com" +
"\n" +
"• AOL: smtp.aol.com" +
"\n" +
"• iCloud: smtp.mail.me.com ou smtp.mail.icloud.com";
        jTextPane1.setText(info_w);
        
 desabilitaCampos();
 host_1.setVisible(true);
 host_2.setVisible(true);
 logEnable();       
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
         info_w = "► Informar a identificação única do usuário deste domínio (Nome de usuário, Endereço de e-mail ou identificador exclusivo).\n\nEste campo é em geral equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema\n\nExemplos:\n\n• Endereço de E-mail: usuario@example.com\n• Nome de Usuário: usuario123\n• Identificadores Exclusivo: Identificador que oculta o usuário.";
         jTextPane1.setText(info_w);
                 desabilitaCampos();

         logEnable();
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
    info_w = "► Informar a senha deste usuário. Pode ser visualizado clicando no checkbox 'Ocultar'.\n\nEste campo é equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema\n\nSe em Propriedades do usuário > Campo Senha E-mail estiver informado. O sistema priorizará este campo ao invés do parâmetro.\n\nPara alguns provedores de e-mail, pode ser necessário criar uma 'Senha de App' ou também caso o usuário utilize autenticação de dois fatores.";
    jTextPane1.setText(info_w);
    desabilitaCampos();
    logEnable();
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

      // TODO add your handling code here:
        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
            jTextPane1.setText("► Informar a senha deste usuário. Pode ser Ocultado clicando no checkbox 'Ocultar'.\n\nEste campo é equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema");
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(jTextField2.getText().matches("\\d+")){
            
        }else {
            jTextField2.setText("");
        }
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
                if(jTextField2.getText().matches("\\d+")){
            atualizaCampos();
        }else {
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        desabilitaCampos();
    info_w = "► Informar o dominio de e-mail. Ele identifica o servidor de email que gerencia a conta de e-mail deste usuário e direcionar as mensagens de email para o servidor correto.\n\nExemplos:\n\n• Gmail: gmail.com\n• Yahoo: Yahoo.com\n• Microsoft: outlook.com";    
    jTextPane1.setText(info_w);
logEnable();
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        
                if(jTextField1.getText().equals(jTextField6.getText())){
            hideRemotehost();
        } else{
                    showRemotehost();
                }
    atualizaCampos();

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:

            if(jToggleButton1.isSelected()){
            jTextField1.setText(jTextField4.getText());
            jTextField6.setText(jTextField4.getText());
            jTextField7.setText(jTextField6.getText().substring(jTextField6.getText().indexOf('@')+1));
            }
            
            atualizaCampos();
            
                if(jTextField1.getText().equals(jTextField6.getText())){
            hideRemotehost();
        } else{
                    showRemotehost();
                }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked

        // TODO add your handling code here:
            info_w = "► Informar o endereço de e-mail do rementente (Entidade que envia a mensagem de email).";
            jTextPane1.setText(info_w);
            desabilitaCampos();

logEnable();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        info_w = "► Informar o endereço de e-mail do destinatário (Entidade que recebe a mensagem de email).";
                    jTextPane1.setText(info_w);
                        desabilitaCampos();
    if(!jTextField1.getText().equals(jTextField6.getText())){                    
    dominiodestino_1.setVisible(true);
    dominiodestino_2.setVisible(true);
    
    }
    logEnable();
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
        info_w = "► Informar o titulo do e-mail (assunto/subject).";
                                    jTextPane1.setText(info_w);
                                    desabilitaCampos();
                        logEnable();            
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
        info_w = "► Informar o corpo do e-mail.";
        jTextPane1.setText(info_w);
        desabilitaCampos();

logEnable();
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        if (jComboBox1.getSelectedItem().equals("Definir>")){
            jTextField2.setEnabled(true);
        } else {
            jTextField2.setEnabled(false);
        }
        
        porta_w.setText(jComboBox1.getSelectedItem().toString());
        
        if (jComboBox1.getSelectedItem().toString().equals("Definir>")){
            porta_w.setText(jTextField2.getText());
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        info_w = "► Informe qual a porta do Host SMTP destino.\n\nEste campo é equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema \n\nExemplos:\n\n• Gmail:" +
            "                        Porta SMTP segura (SSL/TLS): 465 ou Porta SMTP com STARTTLS: 587" +
            "\n• Outlook/Hotmail:" +
            "      Porta SMTP segura (SSL/TLS): 465 ou Porta SMTP com STARTTLS: 587"+
            "\n• Yahoo:" +
            "                       Porta SMTP segura (SSL/TLS): 465 ou Porta SMTP com STARTTLS: 587\n" +
            "• iCloud:" +
            "                       Porta SMTP segura (SSL/TLS): 465 ou Porta SMTP com STARTTLS: 587";
        
        jTextPane1.setText(info_w);
        
        atualizaCampos();
         desabilitaCampos();
         porta_1.setVisible(true);
         porta_2.setVisible(true);
         logEnable();
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here:
                info_w = "Camada 4 - Transporte.\n\n► Informar o protocolo de segurança criptográfica utilizado na comunicação Cliente e Servidor.\n\nEste campo é equivalente ao Parâmetro [20] - Host SMTP, acessível em administração do sistema > Parametros Função > Menu do Sistema \n\nExemplos:\n\n • SSL (Secure Sockets Layer)\n\n • TLS (Transport Layer Security)";
                jTextPane1.setText(info_w);
                atualizaCampos();
                
         desabilitaCampos();
         cifra_1.setVisible(true);
cifra_2.setVisible(true);
         protocolo_1.setVisible(true);
         protocolo_2.setVisible(true);
         logEnable();
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        atualizaCampos();
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        protocolo_w.setText(jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        atualizaCampos();
        jTextField7.setText(jTextField6.getText().substring(jTextField6.getText().indexOf('@')+1));
                        if(jTextField1.getText().equals(jTextField6.getText())){
            hideRemotehost();
            
        } else{
                    showRemotehost();
                }
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        // TODO add your handling code here:
        atualizaCampos();
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        // TODO add your handling code here:
        atualizaCampos();
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        // TODO add your handling code here:
        parametro.setText("Parâmetro [20] - Host SMTP");
        
    }//GEN-LAST:event_jTextField3MouseEntered

    private void jTextField3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseExited
        // TODO add your handling code here:
        parametro.setText("");
        atualizaCampos();
    }//GEN-LAST:event_jTextField3MouseExited

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
                 desabilitaCampos();
         porta_1.setVisible(true);
         porta_2.setVisible(true);
         logEnable();
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        imageIcon();
        enviarMail mail = new enviarMail(jTextField6.getText(), jTextField1.getText(), jTextField6.getText(), jTextField1.getText(), jPasswordField1.getText(), jTextField3.getText(), jComboBox1.getSelectedItem().toString());
        try {
            logs_w += mail.send();
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(initWindow.class.getName()).log(Level.SEVERE, null, ex);
            logs_w += ex.getMessage()+"\n";
        } catch (AddressException ex) {
            Logger.getLogger(initWindow.class.getName()).log(Level.SEVERE, null, ex);
            logs_w += ex.getMessage()+"\n";
        }


            System.setOut(printStream);
        logs_w += "\n\n";
        logs_w += byteArrayOutputStream.toString();
        jTextPane1.setText(logs_w);
        showAll();
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean hostAtivo(String host){
                try {
            InetAddress address = InetAddress.getByName(host);
            boolean isReachable = address.isReachable(5000); // 5000 milissegundos (5 segundos) de timeout

            if (isReachable) {
                System.out.println("O host " + host + " está ativo.");
                return true;
            } else {
                System.out.println("O host " + host + " não está ativo.");
                return false;
            }
        } catch (Exception e) {
            System.err.println("Erro ao verificar o host: " + e.getMessage());
            return false;
        }
    }
    
    private void salvar_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_bActionPerformed
        // TODO add your handling code here:
        info_w = "";
        inicio_w = "";
        logs_w = "";
        jTextPane1.setText("");
    }//GEN-LAST:event_salvar_bActionPerformed

    private void copiar_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copiar_bActionPerformed
        // TODO add your handling code here:
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        StringSelection selection = new StringSelection(logs_w);
        clipboard.setContents(selection, null);
    }//GEN-LAST:event_copiar_bActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
                    if(jToggleButton1.isSelected()){
            jTextField1.setText(jTextField4.getText());
            jTextField6.setText(jTextField4.getText());
            jTextField7.setText(jTextField4.getText().substring(jTextField4.getText().indexOf('@')+1));
            }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
        // Obtém o diretório atual de onde o JAR está sendo executado
        String diretorioAtual = System.getProperty("user.dir");

        // Nome do arquivo de texto que você deseja criar e salvar
        String nomeArquivo = "arquivo.txt";

        // Caminho completo para o arquivo, incluindo o diretório atual
        String caminhoArquivo = diretorioAtual + "/" + nomeArquivo;

        try {
            // Cria um objeto BufferedWriter para escrever no arquivo
            BufferedWriter writer = new BufferedWriter(new FileWriter(caminhoArquivo));

            // Escreve algum conteúdo no arquivo de texto
            writer.write(logs_w);
            writer.newLine(); // Adiciona uma nova linha

            // Fecha o arquivo
            writer.close();

            System.out.println("Arquivo foi criado e salvo em: " + caminhoArquivo);
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Erro ao criar e salvar o arquivo.");
        }
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
                       JFrame frame = new JFrame("Salvar Arquivo");
        // Nome do arquivo de saída
              JFileChooser fileChooser = new JFileChooser();
                fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

                int result = fileChooser.showOpenDialog(frame);

                if (result == JFileChooser.APPROVE_OPTION) {
                    File selectedDirectory = fileChooser.getSelectedFile();
                    String content = "Conteúdo do arquivo a ser salvo.";

                    // Cria o arquivo e escreve o conteúdo
                    File outputFile = new File(selectedDirectory, "arquivo.txt");
                    try (FileWriter writer = new FileWriter(outputFile)) {
                        writer.write(content);

                    } catch (IOException ex) {

                    }
                }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:
                parametro.setText("Parâmetro [109] - Informe a porta a ser utilizada para envio de e-mail");
    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
        // TODO add your handling code here:
                parametro.setText("");
    }//GEN-LAST:event_jComboBox1MouseExited

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        // TODO add your handling code here:
                        parametro.setText("Parâmetro [109] - Informe a porta a ser utilizada para envio de e-mail");
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jTextField2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseExited
        // TODO add your handling code here:
                        parametro.setText("");
    }//GEN-LAST:event_jTextField2MouseExited

    private void jComboBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseEntered
        // TODO add your handling code here:
                                parametro.setText("Parâmetro [125] - Método de autenticação SSL (e-mail)");
    }//GEN-LAST:event_jComboBox3MouseEntered

    private void jComboBox3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseExited
        // TODO add your handling code here:
                                        parametro.setText("");
    }//GEN-LAST:event_jComboBox3MouseExited

    private void jTextField4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseEntered
        // TODO add your handling code here:
        
                                        parametro.setText("Parâmetro [38] - Nome do USERID do servidor de E-mail");
    }//GEN-LAST:event_jTextField4MouseEntered

    private void jTextField4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseExited
        // TODO add your handling code here:
                                                parametro.setText("");
    }//GEN-LAST:event_jTextField4MouseExited

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
                                                parametro.setText("Parâmetro [38] - Nome do USERID do servidor de E-mail");
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        // TODO add your handling code here:
                                                parametro.setText("");
    }//GEN-LAST:event_jTextField1MouseExited

    private void jPasswordField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseEntered
        // TODO add your handling code here:
        
                                parametro.setText("Parâmetro [40] - Senha para autenticação do SMTP do envio de e-mails");
    }//GEN-LAST:event_jPasswordField1MouseEntered

    private void jPasswordField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseExited
        // TODO add your handling code here:
                                        parametro.setText("");
    }//GEN-LAST:event_jPasswordField1MouseExited

    private void jTextField7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseEntered
        // TODO add your handling code here:
                                        parametro.setText("Dominio do remetente, este campo não é editável.");
    }//GEN-LAST:event_jTextField7MouseEntered

    private void jTextField7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseExited
        // TODO add your handling code here:
        parametro.setText("");
    }//GEN-LAST:event_jTextField7MouseExited

    private void jToggleButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseEntered
        // TODO add your handling code here:
        
                parametro.setText("Preencher os campos 'Dominio', 'Remetente' e 'Destinatário' a partir do 'USERID'");
    }//GEN-LAST:event_jToggleButton1MouseEntered

    private void jToggleButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseExited
        // TODO add your handling code here:
                        parametro.setText("");
    }//GEN-LAST:event_jToggleButton1MouseExited

    private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
        // TODO add your handling code here:
        parametro.setText("Ocultar/mostrar a senha do usuário");
    }//GEN-LAST:event_jCheckBox1MouseEntered

    private void jCheckBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseExited
        // TODO add your handling code here:
                parametro.setText("");
    }//GEN-LAST:event_jCheckBox1MouseExited

    private void jTextField6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseEntered
        // TODO add your handling code here:
        parametro.setText("Endereço de e-mail destino");
    }//GEN-LAST:event_jTextField6MouseEntered

    private void jTextField6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseExited
        // TODO add your handling code here:
        parametro.setText("");
    }//GEN-LAST:event_jTextField6MouseExited

    private void jTextField8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseEntered
        // TODO add your handling code here:
        parametro.setText("Informar o título do e-mail");
    }//GEN-LAST:event_jTextField8MouseEntered

    private void jTextField8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseExited
        // TODO add your handling code here:
        parametro.setText("");
    }//GEN-LAST:event_jTextField8MouseExited

    private void jTextField9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseEntered
        // TODO add your handling code here:
        parametro.setText("Informar o corpo do e-mail");
    }//GEN-LAST:event_jTextField9MouseEntered

    private void jTextField9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseExited
        // TODO add your handling code here:
        parametro.setText("");
    }//GEN-LAST:event_jTextField9MouseExited

    private void logs_b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logs_b1ActionPerformed
        // TODO add your handling code here:
       
        
        if (logs_b1.isSelected()){
           logs_b1.setText("Ocultar");
                    logs_b1.setBackground(new java.awt.Color(102, 153, 255));


        setSize(new java.awt.Dimension(1300, 640));
            logs_b1.setBackground(new java.awt.Color(255, 255, 255));
        
        } else{

        setSize(new java.awt.Dimension(850, 650));
        logs_b1.setText("Detalhes");
            
        }
    }//GEN-LAST:event_logs_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (validateInput()){
            
            if(hostAtivo(jTextField3.getText()) && hostAtivo(jTextField7.getText())){
                    jButton2.setEnabled(true);
                    jButton1.setEnabled(false);
                    hideAll();
                    System.setOut(printStream);
        logs_w += "\n\n";
        logs_w += byteArrayOutputStream.toString();
        jTextPane1.setText(logs_w);
        
        if(!jTextField1.getText().equals(jTextField6.getText())){
        linha1.setVisible(true);
                linha.setVisible(true);
        }

            }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean validateInput(){
               if ((jTextField3.getText().length()>0) && (jTextField4.getText().length()>0) && (jTextField7.getText().length()>0) && (jTextField1.getText().length()>0) && (jTextField6.getText().length()>0) && (jTextField8.getText().length()>0) && (jTextField9.getText().length()>0) && (jPasswordField1.getText().length()>0 || jTextField5.getText().length()>0)){
                   return true;
               } 
               return false;
    }
    
    private void hideAll(){
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField1.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jPasswordField1.setEnabled(false);
        jTextField5.setEnabled(false);
        jComboBox1.setEnabled(false);
        jComboBox3.setEnabled(false);
        jTextField2.setEnabled(false);
        jToggleButton1.setEnabled(false);
        jCheckBox1.setEnabled(false);
    }
    
        private void showAll(){
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField7.setEnabled(true);
        jTextField1.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jPasswordField1.setEnabled(true);
        jTextField5.setEnabled(true);
                jComboBox1.setEnabled(true);
        jComboBox3.setEnabled(true);
                jToggleButton1.setEnabled(true);
        jCheckBox1.setEnabled(true);
        

    }
    
    
    private void logEnable(){

        logs_b1.setBackground(new java.awt.Color(240,240,240));
    }
    

    
    private void atualizaCampos(){
        host_w.setText(jTextField3.getText());
        protocolo_w.setText(jComboBox3.getSelectedItem().toString());
        porta_w.setText(jComboBox1.getSelectedItem().toString());

        
        if(jTextField6.getText().contains("@")){
        dominioDestino_w.setText(jTextField6.getText().substring(jTextField6.getText().indexOf('@')+1));
        
        
        }

    }
    
    private void desabilitaCampos(){

dominiodestino_1.setVisible(false);
dominiodestino_2.setVisible(false);
cifra_1.setVisible(false);
cifra_2.setVisible(false);
protocolo_1.setVisible(false);
protocolo_2.setVisible(false);
porta_1.setVisible(false);
porta_2.setVisible(false);
host_1.setVisible(false);
host_2.setVisible(false);
    }
    
    private void hideRemotehost(){
        jLabel60.setVisible(false);
jLabel38.setVisible(false);
//.setVisible(false);
jLabel22.setVisible(false);
//jLabel62.setVisible(false);
jLabel63.setVisible(false);
jLabel61.setVisible(false);
jLabel46.setVisible(false);
dominioDestino_w.setVisible(false);
jLabel12.setVisible(false);
dominiodestino_2.setVisible(false);
dominiodestino_1.setVisible(false);

jLabel10.setVisible(false);
jLabel13.setVisible(false);
linha.setVisible(false);

jLabel45.setVisible(true);
jLabel29.setVisible(true);

linha1.setVisible(false);
    }
    
    private void showRemotehost(){
jLabel60.setVisible(true);
jLabel38.setVisible(true);
//jLabel71.setVisible(true);
jLabel52.setVisible(true);
//jLabel62.setVisible(true);
jLabel63.setVisible(true);
jLabel61.setVisible(true);
jLabel46.setVisible(true);
dominioDestino_w.setVisible(true);
jLabel12.setVisible(true);
dominiodestino_2.setVisible(true);
dominiodestino_1.setVisible(true);

jLabel10.setVisible(true);

jLabel13.setVisible(true);


jLabel45.setVisible(false);
jLabel29.setVisible(false);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(initWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(initWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(initWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(initWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new initWindow().setVisible(true);
                } catch (NoSuchProviderException ex) {
                    Logger.getLogger(initWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (AddressException ex) {
                    Logger.getLogger(initWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Host;
    private javax.swing.JLabel cifra_1;
    private javax.swing.JLabel cifra_2;
    private javax.swing.JButton copiar_b;
    private javax.swing.JLabel dominioDestino_w;
    private javax.swing.JLabel dominiodestino_1;
    private javax.swing.JLabel dominiodestino_2;
    private javax.swing.JLabel host_1;
    private javax.swing.JLabel host_2;
    private javax.swing.JLabel host_w;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel linha;
    private javax.swing.JLabel linha1;
    private javax.swing.JToggleButton logs_b1;
    private javax.swing.JLabel parametro;
    private javax.swing.JLabel porta_1;
    private javax.swing.JLabel porta_2;
    private javax.swing.JLabel porta_w;
    private javax.swing.JLabel protocolo_1;
    private javax.swing.JLabel protocolo_2;
    private javax.swing.JLabel protocolo_w;
    private javax.swing.JButton salvar_b;
    // End of variables declaration//GEN-END:variables
}
